kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.28.7
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        # imageRepository: registry.aliyuncs.com/google_containers
        networking:
          # serviceSubnet: 10.0.0.0/16
          apiServerAddress: "0.0.0.0"
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 443
        hostPort: 8443
        protocol: TCP
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
    # extraMounts:
    #   - hostPath: ./patches
    #     containerPath: /patches
  - role: worker
    image: kindest/node:v1.28.7
  - role: worker
    image: kindest/node:v1.28.7
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."10.0.0.10:5000"]
      endpoint = ["http://10.0.0.10:5000"]

# kubeadmConfigPatches:
#   - |
#     kind: InitConfiguration
#     patches:
#       directory: /patches
