global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: thanos-sidecar
    replica: prometheus1 # 用于 thanos 的查询过滤

alerting:
  alert_relabel_configs:
    - regex: replica
      action: labeldrop
  alertmanagers:
    - scheme: http
      path_prefix: /
      static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/rules/*rules.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
