services:
  h2:
    build:
      context: .
    ports:
      - "443:443"
    volumes:
      - ./:/pcap
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD-SHELL", "timeout 2 bash -c '</dev/tcp/127.0.0.1/443' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3
