kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  kubeProxyMode: "none"
  podSubnet: "10.244.0.0/16" # kubectl cluster-info dump | grep -m 1 cluster-cidr
  serviceSubnet: "10.96.0.0/16" # kubectl cluster-info dump | grep -m 1 service-cluster-ip-range
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /opt/cni/bin/
        containerPath: /opt/cni/bin
      - hostPath: .
        containerPath: /data
  - role: worker
    extraMounts:
      - hostPath: /opt/cni/bin/
        containerPath: /opt/cni/bin
      - hostPath: .
        containerPath: /data
  - role: worker
    extraMounts:
      - hostPath: /opt/cni/bin/
        containerPath: /opt/cni/bin
      - hostPath: .
        containerPath: /data
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."10.0.0.10:5000"]
      endpoint = ["http://10.0.0.10:5000"]
