services:
  mongo1:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    container_name: mongo1
    # environment:
    #   MONGODB_INITDB_ROOT_USERNAME: root
    #   MONGODB_INITDB_ROOT_PASSWORD: mongodb
    command:
      [
        "--replSet",
        "rs0",
        "--wiredTigerCacheSizeGB",
        "0.5",
        "--oplogSize",
        "100",
      ]
    volumes:
      - mongodata01:/data/db
    ports:
      - 30001:27017
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "--eval",
          "'quit(db.adminCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      start_period: 30s
      timeout: 5s
      retries: 3

  mongo2:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    container_name: mongo2
    # environment:
    #   MONGODB_INITDB_ROOT_USERNAME: root
    #   MONGODB_INITDB_ROOT_PASSWORD: mongodb
    command:
      [
        "--replSet",
        "rs0",
        "--wiredTigerCacheSizeGB",
        "0.5",
        "--oplogSize",
        "100",
      ]
    volumes:
      - mongodata02:/data/db
    ports:
      - 30002:27017
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "--eval",
          "'quit(db.adminCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      start_period: 30s
      timeout: 5s
      retries: 3

  mongo3:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    container_name: mongo3
    # environment:
    #   MONGODB_INITDB_ROOT_USERNAME: root
    #   MONGODB_INITDB_ROOT_PASSWORD: mongodb
    command:
      [
        "--replSet",
        "rs0",
        "--wiredTigerCacheSizeGB",
        "0.5",
        "--oplogSize",
        "100",
      ]
    volumes:
      - mongodata03:/data/db
    ports:
      - 30003:27017
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "--eval",
          "'quit(db.adminCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      start_period: 30s
      timeout: 5s
      retries: 3

volumes:
  mongodata01:
    driver: local
  mongodata02:
    driver: local
  mongodata03:
    driver: local

networks:
  default:
    name: monitoring
