groups:
  - name: database
    rules:
      - alert: HighRequestLatency
        expr: job:request_latency_seconds:mean5m{job="database"} > 0.5
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High request latency
      - record: job:request_latency_seconds:mean5m
        expr: rate(request_latency_seconds_total[5m])
