services:
  redis-node-0:
    image: redis:7.0
    network_mode: host
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --port 7000
    volumes:
      - redis-node-0:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7000", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
  redis-node-1:
    image: redis:7.0
    network_mode: host
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --port 7001
    volumes:
      - redis-node-1:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7001", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
  redis-node-2:
    image: redis:7.0
    network_mode: host
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --port 7002
    volumes:
      - redis-node-2:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7002", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
  redis-node-3:
    image: redis:7.0
    network_mode: host
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --port 7003
    volumes:
      - redis-node-3:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7003", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
  redis-node-4:
    image: redis:7.0
    network_mode: host
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --port 7004
    volumes:
      - redis-node-4:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7004", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
  redis-node-5:
    image: redis:7.0
    network_mode: host
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --port 7005
    volumes:
      - redis-node-5:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7005", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  redis-node-1:
  redis-node-2:
  redis-node-3:
  redis-node-4:
  redis-node-5:
  redis-node-0:
