name: host-gw
topology:
  nodes:
    gw1:
      kind: linux
      image: wbitt/network-multitool
      exec:
        - sysctl -w net.ipv4.ip_forward=1
        - ip addr add 10.1.5.1/24 dev eth1
        - ip addr add 172.12.1.10/24 dev eth2
        - ip route add 10.1.8.0/24 via 172.12.1.11
    gw2:
      kind: linux
      image: wbitt/network-multitool
      exec:
        - sysctl -w net.ipv4.ip_forward=1
        - ip addr add 10.1.8.1/24 dev eth1
        - ip addr add 172.12.1.11/24 dev eth2
        - ip route add 10.1.5.0/24 via 172.12.1.10
    server1:
      kind: linux
      image: wbitt/network-multitool
      exec:
        - ip addr add 10.1.5.10/24 dev net0
        - ip route replace default via 10.1.5.1
    server2:
      kind: linux
      image: wbitt/network-multitool
      exec:
        - ip addr add 10.1.8.10/24 dev net0
        - ip route replace default via 10.1.8.1
  links:
    - endpoints: ["gw1:eth1", "server1:net0"]
    - endpoints: ["gw2:eth1", "server2:net0"]
    - endpoints: ["gw1:eth2", "gw2:eth2"]
