services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elasticsearch
    environment:
      - node.name=node1 # 节点名称
      - cluster.name=es-standalone # 集群名称
      - discovery.type=single-node # 单节点模式
      - bootstrap.memory_lock=true # 防止其内存被交换到硬盘，从而保证其性能。
      - xpack.security.enabled=false # 安全认证
      - path.repo=/usr/share/elasticsearch/backup # 备份路径, 用于快照
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # 堆内存大小
      - ELASTIC_PASSWORD=elastic # 设置密码
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
      # - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -s http://localhost:9200 | grep -q ''"tagline" : "You Know, for Search"''',
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    depends_on:
      elasticsearch:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:8.13.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # - I18N_LOCALE=zh-CN
    # volumes:
    #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  elastic_data:
    driver: local

networks:
  default:
    name: elastic
    driver: bridge
