name: calico-vxlan-cross-subnet
topology:
  nodes:
    gw0:
      kind: linux
      image: wbitt/network-multitool
      exec:
        - sysctl -w net.ipv4.ip_forward=1
        - ip addr add 10.1.5.1/24 dev eth1
        - ip addr add 10.1.8.1/24 dev eth2
        - iptables -t nat -A POSTROUTING -s 10.1.0.0/16 -o eth0 -j MASQUERADE
      binds:
        - .:/data
    br-pool0:
      kind: bridge
    br-pool1:
      kind: bridge
    server1:
      kind: linux
      image: 10.0.0.10:5000/wbitt/network-multitool
      network-mode: container:calico-vxlan-cross-subnet-control-plane
      exec:
        - ip addr add 10.1.5.10/24 dev net0
        - ip route replace default via 10.1.5.1
    server2:
      kind: linux
      image: 10.0.0.10:5000/wbitt/network-multitool
      network-mode: container:calico-vxlan-cross-subnet-worker
      exec:
        - ip addr add 10.1.5.11/24 dev net0
        - ip route replace default via 10.1.5.1
    server3:
      kind: linux
      image: 10.0.0.10:5000/wbitt/network-multitool
      network-mode: container:calico-vxlan-cross-subnet-worker2
      exec:
        - ip addr add 10.1.8.10/24 dev net0
        - ip route replace default via 10.1.8.1
    server4:
      kind: linux
      image: 10.0.0.10:5000/wbitt/network-multitool
      network-mode: container:calico-vxlan-cross-subnet-worker3
      exec:
        - ip addr add 10.1.8.11/24 dev net0
        - ip route replace default via 10.1.8.1
  links:
    - endpoints: ["br-pool0:br-pool0-net0", "server1:net0"]
    - endpoints: ["br-pool0:br-pool0-net1", "server2:net0"]
    - endpoints: ["br-pool1:br-pool1-net0", "server3:net0"]
    - endpoints: ["br-pool1:br-pool1-net1", "server4:net0"]
    - endpoints: ["gw0:eth1", "br-pool0:br-pool0-net2"]
    - endpoints: ["gw0:eth2", "br-pool1:br-pool1-net2"]
