services:
  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:v3.5.13
    entrypoint: /usr/local/bin/etcd
    ports:
      - 2379:2379
    command:
      - "--name=etcd"
      - "--initial-advertise-peer-urls=http://etcd:2380"
      - "--listen-peer-urls=http://0.0.0.0:2380"
      - "--listen-client-urls=http://0.0.0.0:2379"
      - "--advertise-client-urls=http://etcd:2379"
    volumes:
      - etcd1:/etcd_data

volumes:
  etcd1:
