kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.28.7
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        # imageRepository: registry.aliyuncs.com/google_containers
        networking:
          # serviceSubnet: 10.0.0.0/16
          apiServerAddress: "0.0.0.0"
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    # extraPortMappings:
    #   - containerPort: 80
    #     hostPort: 80
    #     listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    #     protocol: tcp # Optional, defaults to tcp
    # extraMounts:
    # - containerPath: /var/lib/kubelet/config.json
    #   hostPath: /path/to/my/secret.json
  - role: worker
    image: kindest/node:v1.28.7
  - role: worker
    image: kindest/node:v1.28.7
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."10.0.0.10:5000"]
      endpoint = ["http://10.0.0.10:5000"]
