# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
# https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  # https://github.com/oliver006/redis_exporter
  # https://github.com/oliver006/redis_exporter/issues/281
  - job_name: redis_exporter
    static_configs:
      - targets: ["redis_exporter:9121"]
