services:
  redis1:
    image: redis:7.0
    network_mode: host
    volumes:
      - "redis1-data:/data:rw"
    command: ["redis-server", "--appendonly", "yes", "--port", "16379"]
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "16379", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  redis2:
    depends_on:
      redis1:
        condition: service_healthy
    image: redis:7.0
    network_mode: host
    volumes:
      - "redis2-data:/data:rw"
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--port",
        "26379",
        "--slaveof",
        "<HOST_IP>",
        "16379",
      ]
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  redis3:
    depends_on:
      redis1:
        condition: service_healthy
    image: redis:7.0
    network_mode: host
    volumes:
      - "redis3-data:/data:rw"
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--port",
        "36379",
        "--slaveof",
        "<HOST_IP>",
        "16379",
      ]
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "36379", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  sentinel1:
    depends_on:
      redis1:
        condition: service_healthy
      redis2:
        condition: service_healthy
      redis3:
        condition: service_healthy
    build:
      context: .
    ports:
      - "0.0.0.0:10001:26379"
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  sentinel2:
    depends_on:
      redis1:
        condition: service_healthy
      redis2:
        condition: service_healthy
      redis3:
        condition: service_healthy
    build:
      context: .
    ports:
      - "0.0.0.0:10002:26379"
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  sentinel3:
    depends_on:
      redis1:
        condition: service_healthy
      redis2:
        condition: service_healthy
      redis3:
        condition: service_healthy
    build:
      context: .
    ports:
      - "0.0.0.0:10003:26379"
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  redis1-data:
  redis2-data:
  redis3-data:

networks:
  default:
    name: monitoring
